const initialState = {
  items: '',
  sales: '',
  inventory: '',
  search: '',
  marker: '',
  name: '',
  price: '',
  unitMeasure: '',
  piecesUnit: '',
  salesGrand: '',
  isMatched: false,

  user: {},
  validName: false,
  userFocus: false,
  pwd: '',
  validPwd: false,
  pwdFocus: false,
  matchPwd: '',
  validMatch: false,
  matchFocus: false,

  errMsg: '',
  alertMsg: '',
  success: false,
  auth: {},
  qty: '',
  getNames: [],
  isEdit: false,
  inItem: {},
  outItem: '',
  afa: '',
  ole: '',
  transArray: [],
  total: 0,
  amount: 0,
  clear: '',
  INCREMENT: '',
  DECREMENT: '',
  cartItem: '',
  cancel: false,
  qtyArray: [],
  cartArray: [],
  checkout: false,
  paidAmount: '',
  balance: 0,
  id: '',
  backendUser: {},
  selectUser: '',
  elItem: {},
  singleItemArray: [],
  cartAmount: 0,
  totalCart: 0,
  isDeleted: false,
  image: '',
  isEdited: false,
  email: '',
  validEmail: false,
  category: ''


}

export default initialState